<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [1]:
import os

In [2]:
datos = os.listdir()
datos

['datos_calidad_vida_multi.xlsx',
 'desktop.ini',
 'documentos varios',
 'laboratorio-modulo2-leccion01-numpy.ipynb',
 'Python - ejercicios 0.zip',
 'python-3.13.0-amd64 (1).exe',
 'python-3.13.0-amd64 (2).exe',
 'python-3.13.0-amd64.exe',
 'VSCodeUserSetup-x64-1.94.0.exe']

In [5]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\fatim\AppData\Local\Temp\ipykernel_13092\1996085454.py:1: SyntaxWarning: invalid escape sequence '\d'
  diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}


NameError: name 'diccioanrio_df' is not defined

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [4]:
import numpy as np


#np.arange(10) genera un array de una dimensión con valores enteros consecutivos que comienzan en 0 y terminan en 9 (excluye el valor superior)
array_1d = np.arange(10)
print("Ejercicio 1 - Array 1D:", array_1d)

import numpy as np
print("Versión de NumPy:", np.__version__)
print("Array de ejemplo:", np.arange(10))


ModuleNotFoundError: No module named 'numpy'

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [ ]:
array_2d = array_1d.reshape(2, 5)
print("\nEjercicio 2 - Array 2D:\n", array_2d)

NameError: name 'array_1d' is not defined

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [ ]:
array = np.array([0, 2, 0, 3, 0, 4, 0])
indices_no_cero = np.nonzero(array)
print("\nEjercicio 3 - Índices de elementos distintos de 0:", indices_no_cero)

NameError: name 'np' is not defined

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [6]:
array_3x3 = np.random.random((3, 3))
print("\nEjercicio 4 - Array 3x3:\n", array_3x3)

NameError: name 'np' is not defined

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [ ]:
array_random = np.random.random(10)
print("\nEjercicio 5 - Array de 10 números aleatorios:", array_random)
print("Máximo:", np.max(array_random))
print("Mínimo:", np.min(array_random))

#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [ ]:

array_invertido = array_1d[::-1]
print("\nEjercicio 6 - Array invertido:", array_invertido)



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [ ]:
array_3d = np.arange(1, 25).reshape(2, 3, 4)
print("\nEjercicio 6 Extra - Array 3D:\n", array_3d)
print("Primer 15:", array_3d[array_3d == 15])
print("Primer array:\n", array_3d[0])
print("Última fila del último array:\n", array_3d[-1, -1])

NameError: name 'np' is not defined


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [ ]:
array_3d_2 = np.arange(1, 31).reshape(3, 2, 5)
print("\nEjercicio 7 - Array 3D:\n", array_3d_2)
print("Dos primeros elementos de cada fila del primer array:\n", array_3d_2[0, :, :2])
print("Todas las filas de los dos últimos arrays:\n", array_3d_2[1:, :, :])

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [ ]:
array_3d_3 = np.arange(1, 25).reshape(4, 3, 2)
array_3d_3[1, 1] = 0
array_3d_3[-1] = -1
print("\nEjercicio 8 - Array 3D modificado:\n", array_3d_3)



NameError: name 'np' is not defined


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [ ]:
array_3d_4 = np.random.randint(-10, 14, size=(2, 4, 3))
print("\nEjercicio 9 - Array 3D:\n", array_3d_4)
print("Elementos mayores a 5:", array_3d_4[array_3d_4 > 5])
array_3d_4[array_3d_4 < 0] = 0
print("Array con valores negativos reemplazados por 0:\n", array_3d_4)

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [ ]:
array_3d_5 = np.arange(1, 28).reshape(3, 3, 3)
print("\nEjercicio 10 - Array 3D:\n", array_3d_5)
print("Subarray del segundo array (dos primeras columnas):\n", array_3d_5[1, :, :2])
print("Elementos mayores que 20 en el tercer array:\n", array_3d_5[2, array_3d_5[2] > 20])

NameError: name 'np' is not defined

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [ ]:
array_random_2 = np.random.random(10)
array_random_2[array_random_2 == np.max(array_random_2)] = 0
array_random_2[array_random_2 == np.min(array_random_2)] = 0
print("\nEjercicio 11 - Array con máximos y mínimos reemplazados por 0:", array_random_2)

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [ ]:
array_random_3 = np.random.randint(1, 101, size=15)
array_sorted = np.sort(array_random_3)
print("\nEjercicio 12 - Array ordenado:", array_sorted)

NameError: name 'np' is not defined

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [ ]:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1159058440.py, line 1)

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [10]:
array_random_3 = np.random.randint(1, 101, size=15)
array_sorted = np.sort(array_random_3)
print("\nEjercicio 12 - Array ordenado:", array_sorted)

NameError: name 'np' is not defined

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [ ]:
array_4x4 = np.random.randint(1, 10, size=(4, 4))
print("\nEjercicio 13 - Matriz 4x4:\n", array_4x4)
print("Suma por filas:", np.sum(array_4x4, axis=1))
print("Suma por columnas:", np.sum(array_4x4, axis=0))

NameError: name 'np' is not defined

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [ ]:
array_5x5 = np.ones((5, 5))
array_5x5[1:-1, 1:-1] = 0
print("\nEjercicio 14 - Matriz 5x5:\n", array_5x5)

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [ ]:
array_random_4 = np.random.random(10)
print("\nEjercicio 15 - Media:", np.mean(array_random_4))
print("Desviación estándar:", np.std(array_random_4))

#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [9]:
import numpy as np

# Generar un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24
array_original = np.arange(1, 25).reshape(3, 2, 4)
print("Array original (3, 2, 4):\n", array_original)

# Realizar una rotación completa de los ejes para convertir la forma a (4, 3, 2)
array_rotado = np.transpose(array_original, axes=(2, 0, 1))
print("\nArray rotado (4, 3, 2):\n", array_rotado)


ModuleNotFoundError: No module named 'numpy'

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [8]:
# Crear un array tridimensional con dimensiones (3, 4, 5) con valores aleatorios entre -10 y 10
array_3d = np.random.randint(-10, 11, size=(3, 4, 5))
print("Array original:\n", array_3d)

# Calcular valores estadísticos
array_min = array_3d.min()
array_max = array_3d.max()
array_median = np.median(array_3d)

# Crear un array vacío con las mismas dimensiones que el array original
array_result = np.empty_like(array_3d, dtype=object)

# Reemplazar valores según las condiciones
for i in range(array_3d.shape[0]):
    for j in range(array_3d.shape[1]):
        for k in range(array_3d.shape[2]):
            value = array_3d[i, j, k]
            if value == array_min:
                array_result[i, j, k] = "MIN"
            elif value == array_max:
                array_result[i, j, k] = "MAX"
            elif value == array_median:
                array_result[i, j, k] = "M"
            elif value > array_median:
                array_result[i, j, k] = "X"
            else:
                array_result[i, j, k] = "Y"

print("\nArray resultado:\n", array_result)


NameError: name 'np' is not defined

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [ ]:
# Crear un array bidimensional de dimensiones 4x4 con valores aleatorios entre 1 y 10
array_4x4 = np.random.randint(1, 11, size=(4, 4))
print("Array 4x4:\n", array_4x4)

# Verificar si alguna fila es igual a alguna columna
rows, cols = array_4x4.shape
fila_columna_igual = False

for i in range(rows):
    for j in range(cols):
        # Comparar la fila `i` con la columna `j` elemento por elemento
        if all(array_4x4[i][k] == array_4x4[k][j] for k in range(rows)):
            print(f"Fila {i} es igual a Columna {j}")
            fila_columna_igual = True

if not fila_columna_igual:
    print("No hay ninguna fila que sea igual a una columna.")
